# Generated by Django 5.2.4 on 2025-07-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['surname', 'name'], name='customers_c_surname_e0ea7b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='customers_c_email_c1e1d4_idx'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='customers.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='promocodeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='promocodeclient',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.promocode'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='promocodeusage',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.promocode'),
        ),
        migrations.AddIndex(
            model_name='bonus',
            index=models.Index(fields=['expires_at', 'is_active'], name='customers_b_expires_33b023_idx'),
        ),
    ]
