# Generated by Django 5.2.4 on 2025-07-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
       
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_order',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Новый товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Распродажный товар'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_order',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип размера'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Значение размера'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать в каталоге'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Товар'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
