# Generated by Django 5.2.4 on 2025-07-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_image/', verbose_name='Изображение'),
        ),
    ]
