# Generated by Django 5.2.4 on 2025-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
    ]
