# Generated by Django 5.2.4 on 2025-07-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Текущая цена'),
        ),
    ]
