# Generated by Django 5.2.4 on 2025-07-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productvariant_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Текущая цена'),
        ),
    ]
