# Generated by Django 5.2.4 on 2025-07-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='current_price',
        ),
    ]
