# Generated by Django 5.2.4 on 2025-07-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Текущая цена'),
            preserve_default=False,
        ),
    ]
