# Generated by Django 5.2.4 on 2025-07-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена'),
        ),
    ]
