# Generated by Django 5.2.4 on 2025-07-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_bonus_order_alter_promocodeclient_client_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='parent_order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False, null=True, verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_at',
            field=models.DateField(auto_created=True, null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.TextField(null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Выполнен'), ('not_completed', 'Невыполнен')], default='draft', null=True, verbose_name='Статус заказа'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
