# Generated by Django 5.2.4 on 2025-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма корзины'),
        ),
    ]
