# Generated by Django 5.2.4 on 2025-08-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateField(auto_created=True, blank=True, null=True, verbose_name='Дата создания заказа')),
                ('update_at', models.DateField(auto_created=True, verbose_name='Дата обновления корзины')),
                ('create_at', models.DateField(auto_created=True, verbose_name='Дата создания корзины')),
                ('cart_total_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма корзины')),
                ('is_ordered', models.BooleanField(default=False, null=True, verbose_name='Заказ')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Выполнен'), ('not_completed', 'Невыполнен')], default='draft', null=True, verbose_name='Статус заказа')),
                ('shipping_address', models.TextField(null=True, verbose_name='Адрес доставки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товаров в корзине')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['-pk'],
            },
        ),
    ]
