# Generated by Django 5.2.4 on 2025-08-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_client_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Выполнен'), ('not_completed', 'Не выполнен')], default='draft', null=True, verbose_name='Статус заказа'),
        ),
    ]
