# Generated by Django 5.2.4 on 2025-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='create_at',
            field=models.DateField(auto_created=True, auto_now_add=True, verbose_name='Дата создания корзины'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='update_at',
            field=models.DateField(auto_created=True, auto_now=True, verbose_name='Дата обновления корзины'),
        ),
    ]
