# Generated by Django 5.2.4 on 2025-09-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.PositiveIntegerField(db_index=True)),
                ('amount', models.PositiveIntegerField()),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(default='NEW', max_length=32)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('raw_init_resp', models.JSONField(blank=True, null=True)),
                ('raw_last_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cart_id', 'status'], name='payments_pa_cart_id_475fcc_idx')],
            },
        ),
    ]
