# Generated by Django 5.2.4 on 2025-10-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'История платежей'},
        ),
    ]
