# Generated by Django 5.2.4 on 2025-07-31 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='orders.cart', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='promocodeclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='promocodeclient',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.promocode', verbose_name='Промокод'),
        ),
    ]
