# Generated by Django 5.2.4 on 2025-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_client_slug_alter_client_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма скидки (в %)'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма скидки (в руб.)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона клиента'),
        ),
    ]
