# Generated by Django 5.2.4 on 2025-08-21 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_promocode_amount_promocode_sale_and_more'),
        ('orders', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-expires_at'], 'verbose_name': 'Бонусы', 'verbose_name_plural': 'История бонусов'},
        ),
        migrations.AlterField(
            model_name='bonus',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='orders.cart', verbose_name='Заказ'),
        ),
        migrations.AlterUniqueTogether(
            name='promocodeusage',
            unique_together={('client', 'promocode')},
        ),
    ]
