# Generated by Django 5.2.4 on 2025-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_bonus_options_alter_bonus_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer', verbose_name='Изображение клиента'),
        ),
    ]
