# Generated by Django 5.2.4 on 2025-10-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_client_image'),
        ('orders', '0004_alter_cart_create_at_alter_cart_update_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bonus',
            constraint=models.UniqueConstraint(fields=('order',), name='uniq_bonus_per_order'),
        ),
    ]
